### ISSUE TITLE
Notes from meeting

### ISSUE THREAD

**Issue by jkarni** [radicle-dev/radicle#186]
Website/Github
- [x] Link to github from radicle.xyz
- [x] Remove cgit link
- [x] Remove sample code from radicle.xyz
- [ ] Link to `docs.radicle.xyz` from `radicle.xyz`
- [x] Link to `docs.radicle.xyz` from README

Documentation
- [ ] GHCJS on docs
- [ ] Finish or remove chain example from docs
- [ ] Fix indexing in docs
- [x] Why isn't the issues doc appearing in `docs.radicle.xyz`?
- [ ] Mention that `;;` is for comments early on, and what `expr ;; ==> val` means
- [ ] Note in docs.radicle.xyz getting started that after `stack install` you might need to change your path

Build

- [x] Mention `apt-get install libpq-dev`/`brew install postgresql`
- [x] Maybe make the centralized server not buildable by default (wontfix - annoying for developers)
- [x] Don't build `doc` and `ref-doc` by default (and maybe `radicle-server`) (wontfix - annoying for developers)
- [x] Rename `doc` and `ref-doc` to `radicle-doc` and `radicle-ref-doc`

Installation

- [x] Binary distributions (Now #220)
- [x] Write a script for installing everything (Now #219)

Bugs

- [x] Empty (or only comment) lines result in parse error. They shouldn't. (Now #218)

Improvements

- [x] Rename `config`/`configuration` 
- [x] Make "config" a positional argument
- [x] Don't print test results
- [x] Merge `radicle` and `radicle-client`
- [x] Give better error messages when the default config file is missing
- [x] Mention in CLI help what the default config file is
- [x] Mention in CLI help what the default hist file is

Will be updating as more comes

**Comment by jkarni** [comment]
@juliendonck @xla anything I missed? I'll start splitting this into separate tasks (or just doing the small ones)

**Comment by jameshaydon** [comment]
Improvements to docs captured in #608.
